/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    'perfis-acesso': PerfisAcesso;
    midia: Midia;
    'banners-pagina-inicial': BannersPaginaInicial;
    'motos-novas': MotosNova;
    'motos-seminovas': MotosSeminova;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    'perfis-acesso': PerfisAcessoSelect<false> | PerfisAcessoSelect<true>;
    midia: MidiaSelect<false> | MidiaSelect<true>;
    'banners-pagina-inicial': BannersPaginaInicialSelect<false> | BannersPaginaInicialSelect<true>;
    'motos-novas': MotosNovasSelect<false> | MotosNovasSelect<true>;
    'motos-seminovas': MotosSeminovasSelect<false> | MotosSeminovasSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'dados-institucionais': DadosInstitucionai;
    parametros: Parametro;
  };
  globalsSelect: {
    'dados-institucionais': DadosInstitucionaisSelect<false> | DadosInstitucionaisSelect<true>;
    parametros: ParametrosSelect<false> | ParametrosSelect<true>;
  };
  locale: null;
  user: Usuario & {
    collection: 'usuarios';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nome?: string | null;
  /**
   * Define o grupo de permissões aplicado ao usuário
   */
  perfilAcesso?: (number | null) | PerfisAcesso;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perfis-acesso".
 */
export interface PerfisAcesso {
  id: number;
  nome: string;
  descricao?: string | null;
  /**
   * Quanto menor o número, maior o nível de acesso
   */
  nivelHierarquia: number;
  permissoesColecoes?:
    | {
        colecao: 'usuarios' | 'midia' | 'banners-pagina-inicial';
        podeListar?: boolean | null;
        podeCriar?: boolean | null;
        podeEditar?: boolean | null;
        podeExcluir?: boolean | null;
        id?: string | null;
      }[]
    | null;
  permissoesMenus?:
    | {
        /**
         * Identificador do menu (slug ou chave interna)
         */
        menu: string;
        podeAcessar?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia".
 */
export interface Midia {
  id: number;
  /**
   * Descrição da imagem para acessibilidade
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners-pagina-inicial".
 */
export interface BannersPaginaInicial {
  id: number;
  /**
   * Descrição interna para identificação (não exibido no site)
   */
  descricao?: string | null;
  titulo?: string | null;
  subtitulo?: string | null;
  /**
   * Link para onde o banner deve direcionar ao ser clicado
   */
  bannerUrl?: string | null;
  /**
   * Imagem principal para desktop (1920x800 recomendado)
   */
  imagemDesktop: number | Midia;
  /**
   * Imagem específica para dispositivos móveis (780x840 recomendado)
   */
  imagemMobile?: (number | null) | Midia;
  /**
   * Data a partir da qual o banner deve ser exibido no site
   */
  dataValidadeInicial?: string | null;
  /**
   * Após essa data, o banner será ocultado do site
   */
  dataValidadeFinal?: string | null;
  textoLegal?: string | null;
  /**
   * Define a ordem de exibição do banner; números menores aparecem primeiro
   */
  ordem?: number | null;
  /**
   * Desmarque para ocultar o banner do site
   */
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "motos-novas".
 */
export interface MotosNova {
  /**
   * Identificador único da moto (ex.: biz-125, cg-160). Usado nas URLs e APIs
   */
  id: string;
  /**
   * Nome da moto (ex.: Biz 125, CG 160)
   */
  nome: string;
  /**
   * Se desmarcado, a moto não aparecerá no site
   */
  ativo?: boolean | null;
  /**
   * Cadastre os diferentes modelos/variações desta moto (ex.: ES, EX, Sport, Flex)
   */
  modelos: {
    /**
     * Nome/versão do modelo (ex.: ES, EX, Sport, Flex)
     */
    nome: string;
    dadosFinanceiros: {
      /**
       * Preço de venda à vista do modelo (em reais)
       */
      preco: number;
      /**
       * Cadastre as opções de parcelamento do financiamento disponíveis (opcional)
       */
      parcelamento?:
        | {
            /**
             * Número de parcelas (meses)
             */
            qtdParcelas: number;
            /**
             * Valor de cada parcela (em reais)
             */
            precoParcela: number;
            /**
             * Calculado automaticamente (quantidade × valor da parcela). Campo somente leitura.
             */
            precoTotal?: number | null;
            id?: string | null;
          }[]
        | null;
      /**
       * Preço promocional quando aplicável (normalmente menor que o preço à vista)
       */
      precoOferta?: number | null;
      /**
       * Liste as vantagens/diferenciais da oferta (ex.: Promoção para pagamento à vista, Estoque limitado)
       */
      vantagensOferta?:
        | {
            vantagem: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Se marcado, este modelo aparecerá na seção de consórcio do site
     */
    exibirConsorcio?: boolean | null;
    /**
     * Se marcado, este modelo aparecerá na seção de ofertas especiais do site
     */
    exibirOferta?: boolean | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "motos-seminovas".
 */
export interface MotosSeminova {
  /**
   * Identificador único da moto (ex.: nc-750x-preta-2020). Usado nas URLs e APIs
   */
  id: string;
  /**
   * Se desmarcado, a moto não aparecerá no site
   */
  ativo?: boolean | null;
  /**
   * Placa da moto (ex.: ABC-1234)
   */
  placa: string;
  /**
   * Marca da moto (ex.: Honda)
   */
  marca: string;
  /**
   * Nome completo da moto (ex.: NC 750X)
   */
  nome: string;
  /**
   * Ano em que a moto foi fabricada
   */
  anoFabricacao: number;
  /**
   * Ano do modelo da moto
   */
  anoModelo: number;
  /**
   * Quilometragem da moto (ex.: 15000 ou 15.000 km)
   */
  quilometragem: string;
  /**
   * Tipo de combustível
   */
  combustivel: 'Gasolina' | 'Álcool' | 'Flex' | 'Elétrico';
  /**
   * Cor da moto (ex.: Preta, Vermelha)
   */
  cor: string;
  /**
   * Categoria/tipo da moto
   */
  categoria: 'City' | 'Scooter' | 'Naked' | 'Trail' | 'Big Trail' | 'Crossover' | 'Off Road' | 'Sport' | 'Touring';
  /**
   * Preço de venda da moto (em reais)
   */
  preco: number;
  /**
   * Selecione a filial onde a moto está disponível
   */
  local: string;
  /**
   * Liste as principais características da moto (ex.: Baixa manutenção, Econômica, Único dono)
   */
  caracteristicas?:
    | {
        caracteristica: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Liste os adicionais e diferenciais da moto (ex.: 3 meses de garantia, Transferência gratuita)
   */
  adicionais?:
    | {
        adicional: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Imagem principal da moto exibida nas listagens e cards
   */
  imagem?: (number | null) | Midia;
  /**
   * Galeria com fotos adicionais da moto (opcional)
   */
  galeria?:
    | {
        imagem: number | Midia;
        /**
         * Descrição da imagem para acessibilidade (ex.: NC 750X foto 1)
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'perfis-acesso';
        value: number | PerfisAcesso;
      } | null)
    | ({
        relationTo: 'midia';
        value: number | Midia;
      } | null)
    | ({
        relationTo: 'banners-pagina-inicial';
        value: number | BannersPaginaInicial;
      } | null)
    | ({
        relationTo: 'motos-novas';
        value: string | MotosNova;
      } | null)
    | ({
        relationTo: 'motos-seminovas';
        value: string | MotosSeminova;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nome?: T;
  perfilAcesso?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "perfis-acesso_select".
 */
export interface PerfisAcessoSelect<T extends boolean = true> {
  nome?: T;
  descricao?: T;
  nivelHierarquia?: T;
  permissoesColecoes?:
    | T
    | {
        colecao?: T;
        podeListar?: T;
        podeCriar?: T;
        podeEditar?: T;
        podeExcluir?: T;
        id?: T;
      };
  permissoesMenus?:
    | T
    | {
        menu?: T;
        podeAcessar?: T;
        id?: T;
      };
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "midia_select".
 */
export interface MidiaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners-pagina-inicial_select".
 */
export interface BannersPaginaInicialSelect<T extends boolean = true> {
  descricao?: T;
  titulo?: T;
  subtitulo?: T;
  bannerUrl?: T;
  imagemDesktop?: T;
  imagemMobile?: T;
  dataValidadeInicial?: T;
  dataValidadeFinal?: T;
  textoLegal?: T;
  ordem?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "motos-novas_select".
 */
export interface MotosNovasSelect<T extends boolean = true> {
  id?: T;
  nome?: T;
  ativo?: T;
  modelos?:
    | T
    | {
        nome?: T;
        dadosFinanceiros?:
          | T
          | {
              preco?: T;
              parcelamento?:
                | T
                | {
                    qtdParcelas?: T;
                    precoParcela?: T;
                    precoTotal?: T;
                    id?: T;
                  };
              precoOferta?: T;
              vantagensOferta?:
                | T
                | {
                    vantagem?: T;
                    id?: T;
                  };
            };
        exibirConsorcio?: T;
        exibirOferta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "motos-seminovas_select".
 */
export interface MotosSeminovasSelect<T extends boolean = true> {
  id?: T;
  ativo?: T;
  placa?: T;
  marca?: T;
  nome?: T;
  anoFabricacao?: T;
  anoModelo?: T;
  quilometragem?: T;
  combustivel?: T;
  cor?: T;
  categoria?: T;
  preco?: T;
  local?: T;
  caracteristicas?:
    | T
    | {
        caracteristica?: T;
        id?: T;
      };
  adicionais?:
    | T
    | {
        adicional?: T;
        id?: T;
      };
  imagem?: T;
  galeria?:
    | T
    | {
        imagem?: T;
        alt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dados-institucionais".
 */
export interface DadosInstitucionai {
  id: number;
  nome: string;
  nomeFantasia: string;
  /**
   * CNPJ da empresa (será formatado automaticamente)
   */
  cnpj: string;
  /**
   * URL completa do site (ex.: https://exemplo.com)
   */
  siteUrl: string;
  logoConcessionaria: number | Midia;
  logoConcessionariaBranca: number | Midia;
  logoConcessionariaPreta: number | Midia;
  /**
   * Google Tag Manager Container ID (ex.: GTM-XXXXXXX)
   */
  gtmId?: string | null;
  /**
   * Google Analytics 4 Measurement ID (ex.: G-XXXXXXXXXX)
   */
  ga4Id?: string | null;
  concessionarias?:
    | {
        nome: string;
        endereco: {
          /**
           * CEP do endereço (será formatado automaticamente)
           */
          cep: string;
          rua: string;
          numero: string;
          bairro: string;
          cidade: string;
          estado: string;
        };
        /**
         * Ex.: https://maps.google.com/maps?q=moto%20e%20cia%20jardim%20inga&t=m&z=12&output=embed&iwloc=near
         */
        googleMapUrl: string;
        telefones?:
          | {
              /**
               * Ex.: Telefone, Fixo, WhatsApp
               */
              rotulo: string;
              /**
               * Código internacional (ex.: 55 para Brasil)
               */
              codigoPais: string;
              /**
               * Digite o número com DDD. Será formatado automaticamente (ex.: (11) 98765-4321)
               */
              numero: string;
              temWhatsapp?: boolean | null;
              id?: string | null;
            }[]
          | null;
        emails: {
          emailContato: string;
          emailRH?: string | null;
          emailVendas?: string | null;
          emailSeminovas?: string | null;
          emailTestRide?: string | null;
        };
        horarios?:
          | {
              /**
               * Ex.: Segunda a Sexta
               */
              dias: string;
              /**
               * Ex.: 08:00 - 18:00
               */
              horario: string;
              id?: string | null;
            }[]
          | null;
        leadsConnectMyHonda: {
          myHondaDealerCode: number;
          /**
           * Usado no botão flutuante de WhatsApp em todo o site (multi-concessionária)
           */
          whatsappLeadsConnectUrl: string;
          /**
           * Usado nos formulários da página de consórcio (MyHonda)
           */
          leadsConnectFormularioCompletoUrl: string;
          /**
           * Usado nos formulários da página de motos novas (vendas)
           */
          leadsConnectVendasUrl: string;
          /**
           * Usado nos formulários da página de test ride (agendamento de test drive)
           */
          leadsConnectTestRideUrl: string;
          /**
           * Usado nos formulários da página de seguros
           */
          leadsConnectSegurosUrl: string;
          /**
           * Usado nos formulários e botões de agendamento de serviços (revisão, manutenção)
           */
          agendamentoDigitalHondaUrl: string;
          /**
           * Usado nos botões e links da página de peças genuínas Honda
           */
          pecasHondaUrl: string;
        };
        /**
         * Adicione fotos da concessionária para exibição no site
         */
        fotos?:
          | {
              imagem: number | Midia;
              /**
               * Marque apenas uma foto como principal para destaque
               */
              fotoPrincipal?: boolean | null;
              /**
               * Ordem de exibição (números menores aparecem primeiro)
               */
              ordem?: number | null;
              id?: string | null;
            }[]
          | null;
        redesSociais?: {
          /**
           * Ex.: https://instagram.com/hondabymoto
           */
          instagram?: string | null;
          /**
           * Ex.: https://facebook.com/hondabymoto
           */
          facebook?: string | null;
          /**
           * Ex.: https://youtube.com/@hondabymoto
           */
          youtube?: string | null;
          /**
           * Ex.: https://linkedin.com/company/hondabymoto
           */
          linkedin?: string | null;
        };
        /**
         * Marque se esta é a concessionária matriz
         */
        matriz?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametros".
 */
export interface Parametro {
  id: number;
  /**
   * Se desabilitado, oculta toda a seção de motos seminovas do site
   */
  habilitarSeminovos: boolean;
  /**
   * Exibe o botão TENHO INTERESSE no header (versão desktop)
   */
  exibirTenhoInteresseHeader: boolean;
  /**
   * Controla a exibição de preços nos cards de motos novas (Grid/Carousel)
   */
  exibirPrecoMotosNovas: boolean;
  /**
   * Exibe cards separados por modelo/variação (similar ao grid de ofertas)
   */
  exibirModelosSeparadosMotosNovasGrid: boolean;
  /**
   * Exibe cards separados por modelo/variação (similar ao grid de ofertas)
   */
  exibirModelosSeparadosConsorcioGrid: boolean;
  /**
   * Se ativo, usa o valor da parcela com seguro para o menor valor exibido no consórcio
   */
  utilizarParcelasConsorcioComSeguro: boolean;
  /**
   * Se ativo, carrega as tags do Google Tag Manager no site
   */
  habilitarTagsGTM: boolean;
  /**
   * Se ativo, o card de compartilhamento resume as informações. Se desativado, exibe listas completas
   */
  seminovasCardCompartilhadoResumirInformacoes: boolean;
  /**
   * Título padrão usado no <title> e meta tags (fallback global)
   */
  tituloPadraoSite: string;
  /**
   * Meta description padrão usada no layout (fallback global)
   */
  descricaoPadraoSite: string;
  /**
   * Altura do logo da concessionária no header (ex.: 68px, 4rem)
   */
  alturaLogoConcessionariaHeader: string;
  /**
   * Altura do logo da concessionária no footer (ex.: 68px, 4rem)
   */
  alturaLogoConcessionariaFooter: string;
  /**
   * Se ativo, usa a logo da concessionária no header mobile. Se desativado, usa texto com nome fantasia
   */
  usarLogoConcessionariaHeaderMobile: boolean;
  /**
   * Define qual tipo de formulário será usado para leads de motos novas
   */
  motosNovasTipoForm: 'LeadsConnect' | 'WebToLead';
  /**
   * Define qual tipo de formulário será usado para Test Ride
   */
  testRideTipoForm: 'Email' | 'LeadsConnect';
  /**
   * Se ativo, os formulários WebToLead usarão o ambiente de teste da Salesforce
   */
  webToLeadFormsTest: boolean;
  /**
   * Se ativo, o WhatsApp flutuante exibe menu expansível com links separados por concessionária
   */
  separarWhatsAppLeadsConnectPorFilial: boolean;
  /**
   * Se ativo, oculta o botão do WhatsApp no header mobile, exibindo apenas o botão de telefone
   */
  ocultarWhatsappHeaderMobile: boolean;
  /**
   * Texto exibido no botão principal dos cards de motos novas
   */
  cardMotosNovasTextoBotao: string;
  /**
   * Controla quando o botão fica sempre visível (sem hover)
   */
  cardMotosNovasExibirBotaoFixo: 'nenhum' | 'xs' | 'todos';
  /**
   * Texto exibido no botão principal dos cards de motos seminovas
   */
  cardMotosSeminovasTextoBotao: string;
  /**
   * Controla quando o botão fica sempre visível (sem hover)
   */
  cardMotosSeminovasExibirBotaoFixo: 'nenhum' | 'xs' | 'todos';
  /**
   * Texto exibido no botão principal dos cards de ofertas
   */
  cardOfertasTextoBotao: string;
  /**
   * Controla quando o botão fica sempre visível (sem hover)
   */
  cardOfertasExibirBotaoFixo: 'nenhum' | 'xs' | 'todos';
  /**
   * Texto exibido no botão principal dos cards de consórcio
   */
  cardConsorcioTextoBotao: string;
  /**
   * Controla quando o botão fica sempre visível (sem hover)
   */
  cardConsorcioExibirBotaoFixo: 'nenhum' | 'xs' | 'todos';
  /**
   * Texto exibido no botão principal dos cards de serviços
   */
  cardServicosTextoBotao: string;
  /**
   * Controla quando o botão fica sempre visível (sem hover)
   */
  cardServicosExibirBotaoFixo: 'nenhum' | 'xs' | 'todos';
  /**
   * Ajuste a ordem arrastando as seções. As seções aparecerão nesta ordem após o banner principal
   */
  secoesHomeOrdem: {
    secao: 'motos-novas' | 'ofertas' | 'consorcio' | 'test-ride' | 'motos-seminovas' | 'servicos';
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dados-institucionais_select".
 */
export interface DadosInstitucionaisSelect<T extends boolean = true> {
  nome?: T;
  nomeFantasia?: T;
  cnpj?: T;
  siteUrl?: T;
  logoConcessionaria?: T;
  logoConcessionariaBranca?: T;
  logoConcessionariaPreta?: T;
  gtmId?: T;
  ga4Id?: T;
  concessionarias?:
    | T
    | {
        nome?: T;
        endereco?:
          | T
          | {
              cep?: T;
              rua?: T;
              numero?: T;
              bairro?: T;
              cidade?: T;
              estado?: T;
            };
        googleMapUrl?: T;
        telefones?:
          | T
          | {
              rotulo?: T;
              codigoPais?: T;
              numero?: T;
              temWhatsapp?: T;
              id?: T;
            };
        emails?:
          | T
          | {
              emailContato?: T;
              emailRH?: T;
              emailVendas?: T;
              emailSeminovas?: T;
              emailTestRide?: T;
            };
        horarios?:
          | T
          | {
              dias?: T;
              horario?: T;
              id?: T;
            };
        leadsConnectMyHonda?:
          | T
          | {
              myHondaDealerCode?: T;
              whatsappLeadsConnectUrl?: T;
              leadsConnectFormularioCompletoUrl?: T;
              leadsConnectVendasUrl?: T;
              leadsConnectTestRideUrl?: T;
              leadsConnectSegurosUrl?: T;
              agendamentoDigitalHondaUrl?: T;
              pecasHondaUrl?: T;
            };
        fotos?:
          | T
          | {
              imagem?: T;
              fotoPrincipal?: T;
              ordem?: T;
              id?: T;
            };
        redesSociais?:
          | T
          | {
              instagram?: T;
              facebook?: T;
              youtube?: T;
              linkedin?: T;
            };
        matriz?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametros_select".
 */
export interface ParametrosSelect<T extends boolean = true> {
  habilitarSeminovos?: T;
  exibirTenhoInteresseHeader?: T;
  exibirPrecoMotosNovas?: T;
  exibirModelosSeparadosMotosNovasGrid?: T;
  exibirModelosSeparadosConsorcioGrid?: T;
  utilizarParcelasConsorcioComSeguro?: T;
  habilitarTagsGTM?: T;
  seminovasCardCompartilhadoResumirInformacoes?: T;
  tituloPadraoSite?: T;
  descricaoPadraoSite?: T;
  alturaLogoConcessionariaHeader?: T;
  alturaLogoConcessionariaFooter?: T;
  usarLogoConcessionariaHeaderMobile?: T;
  motosNovasTipoForm?: T;
  testRideTipoForm?: T;
  webToLeadFormsTest?: T;
  separarWhatsAppLeadsConnectPorFilial?: T;
  ocultarWhatsappHeaderMobile?: T;
  cardMotosNovasTextoBotao?: T;
  cardMotosNovasExibirBotaoFixo?: T;
  cardMotosSeminovasTextoBotao?: T;
  cardMotosSeminovasExibirBotaoFixo?: T;
  cardOfertasTextoBotao?: T;
  cardOfertasExibirBotaoFixo?: T;
  cardConsorcioTextoBotao?: T;
  cardConsorcioExibirBotaoFixo?: T;
  cardServicosTextoBotao?: T;
  cardServicosExibirBotaoFixo?: T;
  secoesHomeOrdem?:
    | T
    | {
        secao?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}